checks:
  addAllBuiltIn: true
  exclude:
    - "no-node-affinity"
    - "no-read-only-root-fs"
    - "no-rolling-update-strategy"
    - "non-existent-service-account"
    - "privileged-ports"
    - "required-annotation-email"
    - "required-label-owner"
    - "unset-cpu-requirements"
    - "unset-memory-requirements"
    - "use-namespace"
