apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: kong
    git:
      url: https://github.com/Kong/charts
      ref: kong-2.39.3
    includePaths:
    - charts/kong/**/*
    - .kube-linter.yaml
- path: helm/kong-app
  contents:
  - path: .
    directory:
      path: vendor/kong/charts/kong
    ignorePaths:
    - Chart.lock
    - Chart.yaml
