apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: kong
    git:
      url: https://github.com/giantswarm/kong-charts-upstream
      ref: main
    includePaths:
    - charts/kong/**/*
- path: helm/kong-app
  contents:
  - path: .
    directory:
      path: vendor/kong/charts/kong
    includePaths:
    - templates/**/*
    - crds/**/*
    - ci/**/*
    - example-values/**/*
    - "*.md"
    ignorePaths:
    - values.schema.json
    - values.yaml
    - .helmignore
    - .kube-linter.yaml
    - Chart.lock
    - Chart.yaml
