{{- if .Values.crds.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kong.name.crdInstall" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-4"
    {{- include "kong.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: "{{ template "kong.name.crdInstall" . }}"
    {{- include "kong.metaLabels" . | nindent 4 }}
    role: "{{ template "kong.CRDInstallSelector" . }}"
{{- end }}
