{{- if .Values.crds.install }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "kong.name.crdInstall" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-1"
    {{- include "kong.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: "{{ template "kong.name.crdInstall" . }}"
    {{- include "kong.metaLabels" . | nindent 4 }}
    role: "{{ template "kong.CRDInstallSelector" . }}"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: "{{ template "kong.name.crdInstall" . }}"
        {{- include "kong.metaLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "kong.name.crdInstall" . }}
      securityContext:
      {{- include "kong.podsecuritycontext" . | nindent 8 }}        
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: kubectl
        image: "{{ .Values.image.registry }}/giantswarm/docker-kubectl:1.23.3"
        command:
        - sh
        - -c
        - |
          set -o errexit ; set -o xtrace ; set -o nounset

          # piping stderr to stdout means kubectl's errors are surfaced
          # in the pod's logs.

          kubectl apply --server-side=true --field-manager='kubectl-client-side-apply' --force-conflicts -f /data/ 2>&1
        volumeMounts:
        - name: {{ template "kong.name.crdInstall" . }}-certificaterequests
          mountPath: /data/certificaterequests.yaml
          subPath: certificaterequests.yaml
        - name: {{ template "kong.name.crdInstall" . }}-certificates
          mountPath: /data/certificates.yaml
          subPath: certificates.yaml
        - name: {{ template "kong.name.crdInstall" . }}-challenges
          mountPath: /data/challenges.yaml
          subPath: challenges.yaml
        - name: {{ template "kong.name.crdInstall" . }}-clusterissuers
          mountPath: /data/clusterissuers.yaml
          subPath: clusterissuers.yaml
        - name: {{ template "kong.name.crdInstall" . }}-issuers
          mountPath: /data/issuers.yaml
          subPath: issuers.yaml
        - name: {{ template "kong.name.crdInstall" . }}-orders
          mountPath: /data/orders.yaml
          subPath: orders.yaml
        resources: {{- toYaml .Values.crds.resources | nindent 10 }}
      volumes:
      - name: {{ template "kong.name.crdInstall" . }}-certificaterequests
        configMap:
          name: {{ template "kong.name.crdInstall" . }}-certificaterequests
          items:
          - key: certificaterequests.yaml
            path: certificaterequests.yaml
      - name: {{ template "kong.name.crdInstall" . }}-certificates
        configMap:
          name: {{ template "kong.name.crdInstall" . }}-certificates
          items:
          - key: certificates.yaml
            path: certificates.yaml
      - name: {{ template "kong.name.crdInstall" . }}-challenges
        configMap:
          name: {{ template "kong.name.crdInstall" . }}-challenges
          items:
          - key: challenges.yaml
            path: challenges.yaml
      - name: {{ template "kong.name.crdInstall" . }}-clusterissuers
        configMap:
          name: {{ template "kong.name.crdInstall" . }}-clusterissuers
          items:
          - key: clusterissuers.yaml
            path: clusterissuers.yaml
      - name: {{ template "kong.name.crdInstall" . }}-issuers
        configMap:
          name: {{ template "kong.name.crdInstall" . }}-issuers
          items:
          - key: issuers.yaml
            path: issuers.yaml
      - name: {{ template "kong.name.crdInstall" . }}-orders
        configMap:
          name: {{ template "kong.name.crdInstall" . }}-orders
          items:
          - key: orders.yaml
            path: orders.yaml
      restartPolicy: Never
  backoffLimit: {{ .Values.crds.backoffLimit }}
{{- end }}
