{{- if .Values.crds.install }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kong.name.crdInstall" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-3"
    {{- include "kong.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: "{{ template "kong.name.crdInstall" . }}"
    {{- include "kong.defaultLabels" . | nindent 4 }}
    role: "{{ template "kong.CRDInstallSelector" . }}"
rules:
- apiGroups:
  - ""
  resources:
  - jobs
  verbs:
  - create
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - delete
  - get
  - patch
- apiGroups:
  - configuration.konghq.com
  resources:
  - kongclusterplugins
  - kongconsumers
  - kongingresses
  - kongplugins
  - tcpingresses
  - udpingresses
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ template "kong.name.crdInstall" . }}
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "kong.name.crdInstall" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-2"
    {{- include "kong.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: "{{ template "kong.name.crdInstall" . }}"
    {{- include "kong.defaultLabels" . | nindent 4 }}
    role: "{{ template "kong.CRDInstallSelector" . }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kong.name.crdInstall" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "kong.name.crdInstall" . }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
