version: 2.1
orbs:
  architect: giantswarm/architect@5.0.0

workflows:
  version: 2
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: "push-to-giantswarm-app-catalog"
          context: "architect"
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "kong-app"
          executor: "app-build-suite"
          persist_chart_archive: true
          filters:
            # Trigger job on git tag.
            tags:
              only: /^v.*/

      - architect/run-tests-with-ats:
          name: execute chart tests
          filters:
            # Do not trigger the job on merge to master.
            branches:
              ignore:
                - main
          requires:
            - push-to-giantswarm-app-catalog

      # Require manual approval for running enterprise tests
      - hold-tests:
          name: hold enterprise tests
          type: approval
          filters:
            # Do not trigger the job on master branch or release tags.
            branches:
              ignore:
                - main
            tags:
              ignore: /^v.*/

      - architect/run-tests-with-ats:
          name: execute enterprise tests
          additional_app-test-suite_flags: "--app-tests-app-config-file=tests/test-values-enterprise.yaml"
          filters:
            # Do not trigger the job on merge to master.
            branches:
              ignore:
                - master
          requires:
            - hold enterprise tests
            - push-to-giantswarm-app-catalog
