version: 2.1
orbs:
  architect: giantswarm/architect@0.8.0

jobs:
  template-chart:
    executor: architect/architect
    steps:
      - architect/helm-chart-template:
          chart: "kong-app"
  test-in-kind:
    environment:
      KUBECONFIG: /tmp/kubeconfig_${CIRCLE_SHA1}.yaml
      KUBECONFIG_INTERNAL: /tmp/internal_kubeconfig_${CIRCLE_SHA1}.yaml
    executor: architect/machine
    steps:
      - checkout
      - architect/machine-install-go
      - architect/integration-test-install-tools:
          kubernetes-version: "v1.17.2"
      - architect/integration-test-create-cluster:
          kubernetes-version: "v1.17.2"
          kind-config: ".circleci/kind.yaml"
      - run:
          name: Get 'internal' kubeconfig
          command: kind get kubeconfig --internal > "${KUBECONFIG_INTERNAL}"
      - run:
          name: Get kubeconfig
          command: kind get kubeconfig > "${KUBECONFIG}"
      - run:
          name: Print Kind Cluster Info
          command: kubectl cluster-info
      - run:
          name: Launch app-operator
          command: |
            kubectl run app-operator --generator=run-pod/v1 --image=quay.io/giantswarm/app-operator -- daemon --service.kubernetes.kubeconfig="${KUBECONFIG_INTERNAL}" --service.kubernetes.incluster="false"
      - run:
          name: Launch chart-operator
          command: kubectl run chart-operator --generator=run-pod/v1 --image=quay.io/giantswarm/chart-operator -- daemon --service.kubernetes.kubeconfig="${KUBECONFIG_INTERNAL}" --server.listen.address="http://127.0.0.1:7000" --service.kubernetes.incluster="false"
      - run:
          name: Launch Helm Test
          command: docker run -ti -v ${PWD}:/src quay.io/giantswarm/helm-chart-testing:v2.4.0 ct lint-and-install --validate-maintainers=false --charts="/src/helm/kong-app"

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - template-chart
      - test-in-kind
      - architect/push-to-app-catalog:
          name: "package and push kong-app chart"
          app_catalog: "giantswarm-incubator-catalog"
          app_catalog_test: "giantswarm-incubator-test-catalog"
          chart: "kong-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
          requires:
            - test-in-kind
