version: 2.1
orbs:
  architect: giantswarm/architect@6.3.2

workflows:
  version: 2
  build:
    jobs:
    - architect/push-to-app-catalog:
        name: push-to-giantswarm-app-catalog
        context: architect
        app_catalog: giantswarm-catalog
        app_catalog_test: giantswarm-test-catalog
        chart: kong-app
        executor: app-build-suite
        persist_chart_archive: true
        filters:
            # Trigger job on git tag.
          tags:
            only: /^v.*/

      # Require manual approval for running oss tests
          branches:
            ignore:
            - main
            - master

    - architect/run-tests-with-ats:
        name: execute chart tests
        filters:
          branches:
            ignore:
            - main
        requires:
        - push-to-giantswarm-app-catalog
