version: 2.1
orbs:
  architect: giantswarm/architect@0.8.5

jobs:
  template-chart:
    executor: architect/architect
    steps:
      - checkout
      - architect/helm-chart-template:
          chart: "kong-app"
      - persist_to_workspace:
          root: .
          paths:
            - helm
  test-in-kind:
    environment:
      KUBECONFIG: /tmp/kubeconfig_${CIRCLE_SHA1}.yaml
      KUBECONFIG_INTERNAL: /tmp/internal_kubeconfig_${CIRCLE_SHA1}.yaml
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}-<< pipeline.git.tag >>
      - run: curl -Lo /tmp/kind-app-testing.sh -q https://github.com/giantswarm/kind-app-testing/raw/master/kind-app-testing.sh
      - run: chmod +x /tmp/kind-app-testing.sh
      - run: mkdir /tmp/bin || true
      - restore_cache:
          key: bin-{{ checksum "/tmp/kind-app-testing.sh" }}
      - run: if [[ ! -f /tmp/bin/kind ]]; then curl -Lo /tmp/bin/kind "https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-$(uname)-amd64" && chmod +x /tmp/bin/kind; fi
      - run: if [[ ! -f /tmp/bin/helm ]]; then curl -Lo /tmp/helm.tar.gz https://get.helm.sh/helm-v2.16.5-linux-amd64.tar.gz && tar zxf /tmp/helm.tar.gz -C /tmp && mv /tmp/linux-amd64/helm /tmp/bin/helm; fi
      - run: if [[ ! -f /tmp/bin/kubectl ]]; then curl -Lo /tmp/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl && chmod +x /tmp/bin/kubectl; fi
      - save_cache:
          key: bin-{{ checksum "/tmp/kind-app-testing.sh" }}
          paths:
            - /tmp/bin
      - run: /tmp/bin/helm init -c
      - run: PATH="/tmp/bin:$PATH" /tmp/kind-app-testing.sh -c kong-app -l
      - run: sudo chown -R circleci.circleci /tmp/kat
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - template-chart
      - test-in-kind:
          requires:
            - template-chart
      - architect/push-to-app-catalog:
          name: "package and push kong-app chart"
          app_catalog: "giantswarm-incubator-catalog"
          app_catalog_test: "giantswarm-incubator-test-catalog"
          chart: "kong-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
          requires:
            - test-in-kind
