version: 2.1
orbs:
  architect: giantswarm/architect@4.0.0

workflows:
  version: 2
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: "push-to-giantswarm-app-catalog"
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "kong-app"
          executor: "app-build-suite"
          # ct_config: ".circleci/ct-config.yaml"
          filters:
            # Trigger job on git tag.
            tags:
              only: /^v.*/
