version: 2.1
orbs:
  architect: giantswarm/architect@4.29.0

workflows:
  version: 2
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: "push-to-giantswarm-app-catalog"
          context: "architect"
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "kong-app"
          executor: "app-build-suite"
          persist_chart_archive: true
          filters:
            # Trigger job on git tag.
            tags:
              only: /^v.*/

      - architect/run-tests-with-ats:
          name: execute chart tests
          resource_class: large
          app-test-suite_version: "195ac3a45f78f42308ac9424fc7a5bf6696d916c"
          app-test-suite_container_tag: "0.2.9-195ac3a45f78f42308ac9424fc7a5bf6696d916c"
          additional_app-test-suite_flags: "--kind-cluster-image=kindest/node:v1.25.3@sha256:f52781bc0d7a19fb6c405c2af83abfeb311f130707a0e219175677e366cc45d1"
          filters:
            # Do not trigger the job on merge to master.
            branches:
              ignore:
                - main
          requires:
            - push-to-giantswarm-app-catalog

      # Require manual approval for running enterprise tests
      - hold-tests:
          name: hold enterprise tests
          type: approval
          filters:
            # Do not trigger the job on master branch or release tags.
            branches:
              ignore:
                - main
            tags:
              ignore: /^v.*/

      - architect/run-tests-with-ats:
          name: execute enterprise tests
          resource_class: large
          app-test-suite_version: "195ac3a45f78f42308ac9424fc7a5bf6696d916c"
          app-test-suite_container_tag: "0.2.9-195ac3a45f78f42308ac9424fc7a5bf6696d916c"
          additional_app-test-suite_flags: "--app-tests-app-config-file=tests/test-values-enterprise.yaml"
          filters:
            # Do not trigger the job on merge to master.
            branches:
              ignore:
                - master
          requires:
            - hold enterprise tests
            - push-to-giantswarm-app-catalog
