version: 2.1
orbs:
  architect: giantswarm/architect@5.5.1

workflows:
  version: 2
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: "push-to-giantswarm-app-catalog"
          context: "architect"
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "kong-app"
          executor: "app-build-suite"
          persist_chart_archive: true
          filters:
            # Trigger job on git tag.
            tags:
              only: /^v.*/

      # Require manual approval for running oss tests
      - hold-tests:
          name: hold OSS tests
          type: approval
          filters:
            branches:
              ignore:
                - main
            tags:
              ignore: /^v.*/

      - architect/run-tests-with-ats:
          name: execute enterprise tests
          additional_app-test-suite_flags: "--app-tests-app-config-file=tests/test-values-enterprise.yaml"
          filters:
            branches:
              ignore:
                - main
          requires:
            - push-to-giantswarm-app-catalog

      - architect/run-tests-with-ats:
          name: execute enterprise tests (1.25)
          additional_app-test-suite_flags: "--app-tests-app-config-file=tests/test-values-enterprise.yaml --kind-cluster-image=kindest/node:v1.25.3@sha256:f52781bc0d7a19fb6c405c2af83abfeb311f130707a0e219175677e366cc45d1"
          filters:
            branches:
              ignore:
                - main
          requires:
            - push-to-giantswarm-app-catalog
      
      - architect/run-tests-with-ats:
          name: execute chart tests
          filters:
            branches:
              ignore:
                - main
          requires:
            - hold OSS tests
            - push-to-giantswarm-app-catalog

      - architect/run-tests-with-ats:
          name: execute chart tests (1.25)
          additional_app-test-suite_flags: "--kind-cluster-image=kindest/node:v1.25.3@sha256:f52781bc0d7a19fb6c405c2af83abfeb311f130707a0e219175677e366cc45d1"
          filters:
            branches:
              ignore:
                - main
          requires:
            - hold OSS tests
            - push-to-giantswarm-app-catalog
