### Changed

- Update Kong chart version to `kong-2.46.0` ([#1200](https://github.com/Kong/charts/pull/1200))
- Update Kong Gateway image to `3.9.0.0-debian`
- Update Kong Ingress Controller version to `3.4.1`
