
{{- if .Values.postgresql.external.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kong.postgresql.fullname" . }}
  labels:
    app: "{{ template "kong.name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  postgresql-password: {{ include "postgresql.password" . | b64enc | quote }}
{{- end }}