apiVersion: v1
kind: Service
metadata:
  name: {{ template "kong.fullname" . }}-metrics
  labels:
    giantswarm.io/monitoring: "true"
spec:
  ports:
  - name: {{ template "kong.fullname" . }}-metrics
    port: 9542
    protocol: TCP
    targetPort: 9542
  selector:
{{- include "kong.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
  clusterIP: None
