{{- if and .Values.deployment.kong.enabled }}
{{- if and .Values.status.enabled (or .Values.status.http.enabled .Values.status.tls.enabled) -}}
{{- $serviceConfig := dict -}}
{{- $serviceConfig := merge $serviceConfig .Values.status -}}
{{- $_ := set $serviceConfig "fullName" (include "kong.fullname" .) -}}
{{- $_ := set $serviceConfig "namespace" (include "kong.namespace" .) -}}
{{- $_ := set $serviceConfig "metaLabels" (include "kong.metaLabels" .) -}}
{{- $_ := set $serviceConfig "selectorLabels" (include "kong.selectorLabels" .) -}}
{{- $_ := set $serviceConfig "serviceName" "metrics" -}}
{{- include "kong.service" $serviceConfig }}
{{- end -}}
{{- end -}}
