{{- if .Values.ingressController.validationController.enabled }}
{{- $cn := printf "%s.%s.svc" (print (include "kong.fullname" .) "-validation") .Release.Namespace }}
{{- $altNames := list ( print (include "kong.fullname" .) "-validation" ) ( printf "%s.%s" (print (include "kong.fullname" .) "-validation") .Release.Namespace ) ( printf "%s.%s.svc" (print (include "kong.fullname" .) "-validation") .Release.Namespace ) -}}
{{- $ca := genCA (printf "%s.%s.svc" (print (include "kong.fullname" .) "-validation") .Release.Namespace) 365 -}}
{{- $cert := genSignedCert $cn nil $altNames 365 $ca -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kong.fullname" . }}-validation
  labels:
    app: {{ template "kong.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ template "kong.fullname" . }}-validation
  labels:
    app: {{ template "kong.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
webhooks:
- name: validations.kong.konghq.com
  rules:
  - apiGroups:
    - configuration.konghq.com
    apiVersions:
    - "*"
    operations:
    - CREATE
    - UPDATE
    resources:
    - kongconsumers
    - kongplugins
  failurePolicy: Fail
  clientConfig:
    service:
      namespace: {{ .Release.Namespace }}
      name: {{ template "kong.fullname" . }}-validation
    caBundle: {{ $ca.Cert | b64enc }}
{{- end }}